---
ID: "7d6367ea-44f0-4a51-80f5-cf027e766a4e"
Parent: "7b61f2a1-306d-4f11-8668-50ebedd38f5e"
Template: "d99a18de-5be0-4989-bf07-295cbf6054a0"
Path: "/sitecore/content/TTS/TileShop/Home/installation-care/pro-brands/products"
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{FBAF1E94-F29D-4DDA-9626-FD99C62A8761}"
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 0
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{B92D18EC-7898-49BC-ADC0-F0404B53CC75}"
          p:before="*"
          s:ds="local:/Data/Category Card with link"
          s:id="{83A6F9F3-8863-4423-B79E-E9356F35496F}"
          s:par="GridParameters&amp;FieldNames&amp;Styles&amp;HeadingSize=h2&amp;HeadingTag=h2&amp;IsPinterestEnable=1&amp;BackgroundColor=Light&amp;CTAColor=Black&amp;CTASize=Small&amp;IsCTATextInCaps=1&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=14"
          s:ph="headless-main" />
        <r
          uid="{7155C32C-BAF6-47A8-8539-49A72CFD03EB}"
          p:after="r[@uid='{B92D18EC-7898-49BC-ADC0-F0404B53CC75}']"
          s:id="{5283878D-861F-4748-8A17-B417BAA1A017}"
          s:ph="headless-main" />
        <r
          uid="{A7DF45C6-A953-4F7A-8AC1-3ED613352C1F}"
          p:after="*[1=2]"
          s:ds="{20D717E4-090F-46C5-8640-2631C477C50A}"
          s:id="{78DE797F-A5C0-477A-B1D5-4C560375F4A6}"
          s:par="GridParameters&amp;FieldNames&amp;Styles=|{4CC2D1CA-7110-4C81-A9B2-7AB19E6D05A5}&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
          s:ph="headless-main" />
      </d>
    </r>
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "110f5633-8531-4524-b25a-6e457ef53101"
      Hint: CategoryIntroduction
      Value: When you insist on the highest quality, use our professional Superior products to get the most professional results. From tile saws to grouts to leveling kits, we&rsquo;ve researched and tested them so you don&rsquo;t have to, and we&rsquo;ve found the best products on the market. Natural stone, ceramic and porcelain tile and grout cleaners and sealers are a must to protect and maintain beautiful tile. The Tile Shop works with Pros like you every day so you can trust that the products we sell are the best around.
    - ID: "18a287ab-4991-4a9c-8366-60e6783cdbc8"
      Hint: AvailableFacets
      Value: |
        {943516E3-9F25-4989-9A6A-1E546D31D953}
        {4EF164C6-D6D1-4AE6-A157-CB7DC06BD379}
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181009T195026Z
    - ID: "2fe36a94-8298-4776-b050-9173f9c84b4d"
      Hint: ProductHierarchy1
      Value: "{6C6150BD-AF0B-45FF-8073-6A9531882B8D}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\markb
    - ID: "59cbee2d-30a2-4a03-9501-2e3e0d4e8ced"
      Hint: PageTitle
      Value: "Pro Products - The Tile Shop"
    - ID: "5cfa40b2-276c-4d69-ae6d-6aae88f51804"
      Hint: CategoryName
      Value: Pro Products
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\smallaya
    - ID: "646fd5c9-7658-4ce3-9e88-ce75a8aef93f"
      Hint: ImageUrl
      Value: "Shot03_ToolTable_V1:Category_Intro_Image"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1113d440-bd9b-477a-ae99-ae8a4bda0314"
    - ID: "a85d2606-c144-4bba-9476-d31d5b8d2d55"
      Hint: NavigationTitle
      Value: Pro Products
    - ID: "abaccecc-b180-44dd-8210-ce99fdce5d73"
      Hint: RelatedLink1
      Value: |
        <link class="" querystring="" id="{606D25CA-5E66-4F34-858B-28EBC6969CEC}" anchor="" target="" title="" linktype="internal" text="Superior" url="/TTS/TileShop/Home/tile/installation-care/pro-brands/superior" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "c062edba-a9e6-405c-a204-82db37a4c2d5"
      Hint: MetaDescription
      Value: Shop a wide range of pro products at The Tile Shop.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240918T090417Z
