---
ID: "4109e2f9-9d94-42ea-a13b-cef2e5f20760"
Parent: "9447e6b2-1c65-4ad3-b7a1-69b11258760a"
Template: "9447e6b2-1c65-4ad3-b7a1-69b11258760a"
Path: /sitecore/templates/Feature/TTS/Components/Tiles/Featured Tiles/Datasource Folder/Tile/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240503T071252Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d3d97840-cf7e-4efa-9e98-6f132be6b634"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240628T071731Z
