---
ID: "3908e7ba-d0ac-4582-9e7f-7871982ebf47"
Parent: "e674a1e9-77dd-40ab-a6c3-d311403aca58"
Template: "e674a1e9-77dd-40ab-a6c3-d311403aca58"
Path: /sitecore/templates/Feature/TTS/Components/IframeComponent/Rendering Parameters/IframeComponent/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3b32bf3a-6568-42dc-9ca6-de36745b4dfd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rohit.gupta1@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240508T185158Z
