---
ID: "9d3e5599-f1e3-4c59-b98a-f604a73fc286"
Parent: "94b4c0b7-7bff-4325-858d-de9734a9aece"
Template: "94b4c0b7-7bff-4325-858d-de9734a9aece"
Path: /sitecore/templates/Feature/TTS/Components/Tiles/Featured Tiles/Datasource Folder/FeaturedTiles/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9447E6B2-1C65-4AD3-B7A1-69B11258760A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240503T070633Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9d14e3e1-8edc-4760-96a8-29891935290d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240503T070902Z
