---
ID: "60171b30-a9df-4967-b001-594de3833f3a"
Parent: "c0bb9840-9860-4275-91fe-12906e031747"
Template: "c0bb9840-9860-4275-91fe-12906e031747"
Path: /sitecore/templates/Feature/TTS/Components/Cards/CategoryCardList/Folder Templates/CategoryCardListFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {9D84023B-0099-4BD0-ACEF-EF2AB7E1F9BB}
    {49FA9F22-A0A4-45FE-9FF8-CFE42056037F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240419T082741Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e2e2ad81-6dbe-48a6-8096-3cf248b85fd7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240419T082756Z
