---
ID: "cbcc4b99-1f35-4e71-a69c-440edc9c3d9b"
Parent: "8b8bc4e1-8927-45c8-a334-03e501e2e694"
Template: "8b8bc4e1-8927-45c8-a334-03e501e2e694"
Path: /sitecore/templates/Feature/TTS/Components/Forgot Password/Rendering Parameters/Forgot Password/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "980cf4c9-e1ca-4d31-8738-91685b5923bd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240515T182647Z
