---
ID: "ffe414a8-c228-4321-b8ae-14bbc00a64c5"
Parent: "84101ba6-07a3-426b-8b77-8172aed8e262"
Template: "84101ba6-07a3-426b-8b77-8172aed8e262"
Path: /sitecore/templates/Feature/TTS/Components/Items Cart/Rendering Parameters/Items Cart/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "301c8363-0c59-41b5-9822-42e6db387724"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240528T084220Z
