---
ID: "9833739f-f2f9-41dd-bb38-9917f35aeb0b"
Parent: "ff2864d4-2853-415d-87ab-502f836ac71e"
Template: "ff2864d4-2853-415d-87ab-502f836ac71e"
Path: /sitecore/templates/Feature/TTS/Components/Company User List/Rendering Parameters/CompanyUserList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c82090a4-123f-43c3-bec8-23f2cea39010"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tanvi.vaid@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240703T125913Z
