---
ID: "b67b9cf7-7236-4e81-9ed0-d75561c45cb3"
Parent: "6f7ce9ac-2e5d-4bd2-865b-369ff13f75b7"
Template: "6f7ce9ac-2e5d-4bd2-865b-369ff13f75b7"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Content/_SecondaryCTATitle/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240414T081901Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "412e10c5-1940-48ed-94ac-406344a3ef39"
    - ID: "a881e366-510f-4fa0-8079-9becfec734bc"
      Hint: CTALabel
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240529T063148Z
