---
ID: "729b5b1f-73f8-4a3e-a437-7b0ec9f683d2"
Parent: "1cc04aeb-0f43-4170-bd7d-b9ce8453f3cf"
Template: "1cc04aeb-0f43-4170-bd7d-b9ce8453f3cf"
Path: /sitecore/templates/Feature/TTS/Components/Cards/Category Cards with Embed Links/Datasource Folder/CategoryCardswithEmbedLinks/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9776BF60-6531-464B-B67B-4DA77789D7C9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240426T045925Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "371505de-f522-45a2-862e-50bc6e86cf41"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240426T050017Z
