---
ID: "29ee17dd-301f-4f0b-96f7-4e589e5ab55f"
Parent: "b1a6f81f-0672-4e1d-a0a3-7a5c735e10fb"
Template: "b1a6f81f-0672-4e1d-a0a3-7a5c735e10fb"
Path: /sitecore/templates/Feature/TTS/Components/Rewards Statements/Rendering Parameters/Rewards Statements/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38c319f2-4dc7-4378-9784-63b468a6bdc9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240628T140646Z
