---
ID: "1858ac93-bcb6-4238-9954-58d3fa735904"
Parent: "457ba1e1-1980-4a5d-80c1-2680ffa54a8d"
Template: "457ba1e1-1980-4a5d-80c1-2680ffa54a8d"
Path: /sitecore/templates/Feature/TTS/Components/No Border Image/Rendering Parameters/No Border Image/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7674542f-c0c3-4099-8ad9-9c2b9203b9ed"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T162107Z
