---
ID: "fcccb7a8-b681-49b5-a26b-53854f73af48"
Parent: "07f9dc7b-f60b-4e98-a71e-6bcbef9eb57a"
Template: "07f9dc7b-f60b-4e98-a71e-6bcbef9eb57a"
Path: /sitecore/templates/Feature/TTS/Components/Order Review/Rendering Parameters/OrderReview/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "504eeaf2-ccae-4a65-84af-8b4d00e4e575"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tanvi.vaid@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240627T062812Z
