---
ID: "3ee8ca77-572b-4065-a569-646f42f2d99b"
Parent: "cfcc4755-6443-49b5-a688-041742e940ca"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: /sitecore/content/TTS/TileShop/Dictionary/Product/Product Name
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: Product_Name
Languages:
- Language: en
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: name
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240706T090631Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5f1dea2a-d5fe-464c-8eec-bd31e83eb0e6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240706T090732Z
