---
ID: "938c3e33-b581-4860-941c-a2e8a289b729"
Parent: "6165c34c-be24-438b-97c0-c2d258983c2f"
Template: "6165c34c-be24-438b-97c0-c2d258983c2f"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Media/_TabletVideo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240414T081852Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a231a27-16a4-41dc-862a-ef32d21c2266"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240722T104207Z
