---
ID: "2ae9d19e-794d-4e5c-95b1-c9511cc96f45"
Parent: "432d8cc1-194b-4d2f-8be0-ffe97e08c93e"
Template: "432d8cc1-194b-4d2f-8be0-ffe97e08c93e"
Path: /sitecore/templates/Feature/TTS/Folders/Country Codes Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3B87128E-17C1-4FFB-A058-2279283FE236}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190729T164055Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\james
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\james
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c0b381b9-cade-4410-b33b-100d8b5221e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\james
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190729T164539Z
