---
ID: "c7877b34-5407-4772-8e37-fc80dc43aff5"
Parent: "04ed4c67-7b3c-4b58-9f07-3d8bb1be55d6"
Template: "04ed4c67-7b3c-4b58-9f07-3d8bb1be55d6"
Path: /sitecore/templates/Feature/TTS/Components/Company User List/Folder Templates/CompanyUserList Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {EA00EC99-DE74-4684-892B-0253CC1AC636}
    {04ED4C67-7B3C-4B58-9F07-3D8BB1BE55D6}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8d5e34d5-69a4-4baf-8c2b-4a6d793aa254"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tanvi.vaid@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240703T125918Z
