---
ID: "d5e2e050-c593-4cad-b929-a239147b3678"
Parent: "ad428183-9c79-4670-8ee8-e805b2ca27a0"
Template: "ad428183-9c79-4670-8ee8-e805b2ca27a0"
Path: /sitecore/templates/Feature/TTS/Components/Payment Works Confirmation/Rendering Parameters/PaymentWorksConfirmation Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "796ebe66-9806-4a8b-afd3-31379aa03eaf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241224T091534Z
