---
ID: "7abf8746-1e56-40cb-b8dc-b3d9f634b406"
Parent: "ffc05cad-df50-494e-a24d-a7070a73ed8a"
Template: "ffc05cad-df50-494e-a24d-a7070a73ed8a"
Path: /sitecore/templates/Feature/TTS/Components/Editorial Gallery/Rendering Parameters/Editorial Gallery Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59b5074a-c31a-4efa-bc11-6f52ff53986b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250217T115721Z
