---
ID: "5d861d2d-4109-4d47-8482-8ee9e19ce1f0"
Parent: "74fdc264-ecc9-40ad-9db6-1d85e5173f1b"
Template: "74fdc264-ecc9-40ad-9db6-1d85e5173f1b"
Path: /sitecore/templates/Feature/TTS/Components/Billing Statements/Rendering Parameters/Billing Statements/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa7a3b5d-b533-49d5-af9c-b48aa03311c5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240708T194238Z
