---
ID: "e2139144-c954-4521-9d26-01f5382a4b8c"
Parent: "4bc15dc7-8a15-4e5a-8ea0-01971c44056e"
Template: "4bc15dc7-8a15-4e5a-8ea0-01971c44056e"
Path: /sitecore/templates/Feature/TTS/Components/Forms/Unsubscribe Form/Rendering Parameters/Unsubscribe Form/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f5f9acf2-7be9-4e1e-aa6c-109064464d31"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T054846Z
