---
ID: "5c4babc9-996b-43c8-9423-1cb6ddbf8fe3"
Parent: "76a37c80-7025-458a-8a19-2b212b55e273"
Template: "76a37c80-7025-458a-8a19-2b212b55e273"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Content/_APIEndPoint/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240414T081901Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5cd7e9b9-66df-411f-a5d3-e009e367096b"
      Hint: APIEndPoint
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6ee0b7aa-fc36-49c2-b448-e323624319cf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T064510Z
