---
ID: "ebb765c5-eb5c-4f92-830d-24e3f5df0cee"
Parent: "f1b7b4b2-1441-449d-b732-c1561aeba4e1"
Template: "f1b7b4b2-1441-449d-b732-c1561aeba4e1"
Path: /sitecore/templates/Feature/TTS/Components/Tiles/Tile Search/Rendering Parameters/Tile Search/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00b590f3-849e-4db3-bd18-c5da4d8a6492"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sharma.varun@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240503T051022Z
