---
ID: "94e00919-11bc-4c6d-b15b-fb514353984e"
Parent: "590f31cd-0795-4a18-b38a-da67000f6140"
Template: "590f31cd-0795-4a18-b38a-da67000f6140"
Path: /sitecore/templates/Feature/TTS/Components/Statement Period/Rendering Parameters/Statement Period/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "91e6adda-178f-4d2f-8259-1e3865036f82"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240705T110138Z
