---
ID: "8ff5c1ce-ecdc-4848-86f1-355150ae6399"
Parent: "2a7cf4f5-dc81-459a-8e94-9f442f8a6f2d"
Template: "2a7cf4f5-dc81-459a-8e94-9f442f8a6f2d"
Path: /sitecore/templates/Feature/TTS/Components/BillingAddress/Rendering Parameters/BillingAddress/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59135e82-0980-49ba-8949-d19d57580388"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tanvi.vaid@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240613T135007Z
