---
ID: "82788ba0-ace0-4076-ac50-359a93674fe7"
Parent: "2efc0404-eb50-4c0b-978b-10d9ec9dd5b6"
Template: "2efc0404-eb50-4c0b-978b-10d9ec9dd5b6"
Path: /sitecore/templates/Feature/TTS/Components/Registration/RegisterProUser/Rendering Parameters/RegisterProUser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8f8d8205-ff12-490c-adc1-99b620f2b76d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T132015Z
