---
ID: "5562fb7b-5ed3-4546-bf68-39e3afba86c5"
Parent: "f7c60a4e-37ee-4a3f-9315-7c4bbe4ea6ad"
Template: "f7c60a4e-37ee-4a3f-9315-7c4bbe4ea6ad"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_IsImageOnRight/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cc01040-a67a-4c81-8707-386a11d08e29"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240426T041307Z
