---
ID: "b383ba58-00c1-48d1-af26-93cb1b2a6d8d"
Parent: "0204d579-605d-40ad-8584-1ca852192bb5"
Template: "0204d579-605d-40ad-8584-1ca852192bb5"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Emarsys/_EmarsysDetail/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240613T120012Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ee8283f8-7a4a-4fb8-8052-77862bbdb757"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240613T120012Z
