---
ID: "7238f239-04c4-4500-ad2c-39c091b0d5f3"
Parent: "7a57f718-ac68-44a5-a2df-a6ea64613bce"
Template: "7a57f718-ac68-44a5-a2df-a6ea64613bce"
Path: /sitecore/templates/Feature/TTS/Components/Payment Credit History/Folder Templates/Payment Credit History Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {E2D5A88A-4766-415F-B7DC-B7E5E0BC8AEB}
    {7A57F718-AC68-44A5-A2DF-A6EA64613BCE}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f6006438-f6b8-4b41-934a-90a1f1ff6298"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240707T070021Z
