---
ID: "18c6ba59-ee73-4a01-ac59-ef4aa1957a17"
Parent: "09ee511d-0ba5-472a-b40f-1b1d9fc6ffb2"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: /sitecore/layout/Renderings/Feature/TTS/Product Card Collection/Product Card Collection
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: ProductCardCollection
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: SXA_MDI/16x16/Promo.png
- ID: "17bb046a-a32a-41b3-8315-81217947611b"
  Hint: ComponentQuery
  Value: |
    query ProductCollectionQuery($datasource: String!, $language: String!) {
      dataSource: item(path: $datasource, language: $language) {
        children {
          results {
             KitOptionTitle: field(name: "KitOptionTitle") {
              jsonValue
             }
    		 DisableSubMenu: field(name: "DisableSubMenu") {
              jsonValue
             }
             ButtonText: field(name: "ButtonText") {
              jsonValue
             }
             ButtonFunctionality: field(name: "ButtonFunctionality") {
              jsonValue
             }
    		 DiscoverRfkId: field(name: "DiscoverRfkId") {
              jsonValue
             }
    		 APIEndPoint: field(name: "APIEndPoint") {
              jsonValue
             }
    		 DefaultItemsPerPageDesktop: field(name: "DefaultItemsPerPageDesktop") {
              jsonValue
             }
    		 DefaultItemsPerPageMobile: field(name: "DefaultItemsPerPageMobile") {
              jsonValue
             }
    		 
          }
        }
        Heading: field(name: "Heading") {
          jsonValue
        }
        MobileHeading: field(name: "MobileHeading") {
          jsonValue
        }
        MainThumbnailImage: field(name: "MainThumbnailImage") {
          jsonValue
        }
        ThumbnailImage1: field(name: "ThumbnailImage1") {
          jsonValue
        }
        ThumbnailImage2: field(name: "ThumbnailImage2") {
          jsonValue
        }
    	ThumbnailImage3: field(name: "ThumbnailImage3") {
          jsonValue
        }
    	ThumbnailImage4: field(name: "ThumbnailImage4") {
          jsonValue
        }
    	ThumbnailImage5: field(name: "ThumbnailImage5") {
          jsonValue
        }
    	ThumbnailImage6: field(name: "ThumbnailImage6") {
          jsonValue
        }
    	ThumbnailImage7: field(name: "ThumbnailImage7") {
          jsonValue
        }
    	ThumbnailImage8: field(name: "ThumbnailImage8") {
          jsonValue
        }
    	ButtonText: field(name: "ButtonText") {
          jsonValue
        }
    	HideSubMenu: field(name: "HideSubMenu") {
          jsonValue
        }
        HideThumbnailImages: field(name: "HideThumbnailImages") {
          jsonValue
        }
    	KitOptionText: field(name: "KitOptionText") {
          jsonValue
        }
    	
    	
    	
    	
    	
    	ExtendedImageDesktopImage1: field(name: "ExtendedImageDesktopImage1") {
          jsonValue
        }
    	ExtendedImageMobileImage1: field(name: "ExtendedImageMobileImage1") {
          jsonValue
        }
    	ExtendedImageTabletImage1: field(name: "ExtendedImageTabletImage1") {
          jsonValue
        }
    	ExtendedImageDesktopImage2: field(name: "ExtendedImageDesktopImage2") {
          jsonValue
        }
    	ExtendedImageMobileImage2: field(name: "ExtendedImageMobileImage2") {
          jsonValue
        }
    	ExtendedImageTabletImage2: field(name: "ExtendedImageMobileImage2") {
          jsonValue
        }
    	ExtendedImageDesktopImage3: field(name: "ExtendedImageDesktopImage3") {
          jsonValue
        }
    	ExtendedImageMobileImage3: field(name: "ExtendedImageMobileImage3") {
          jsonValue
        }
    	ExtendedImageTabletImage3: field(name: "ExtendedImageMobileImage3") {
          jsonValue
        }
    	ExtendedImageHeading: field(name: "ExtendedImageHeading") {
          jsonValue
        }
    	ExtendedImageMobileHeading: field(name: "ExtendedImageMobileHeading") {
          jsonValue
        }
    	ExtendedImageDescription: field(name: "ExtendedImageDescription") {
          jsonValue
        }
    	ExtendedImageMobiledescription: field(name: "ExtendedImageMobiledescription") {
          jsonValue
        }
    	BackgroundColor: field(name: "BackgroundColor") {
          jsonValue
        }
    	
    	
    	
    	DisableExtendedProductCarousel: field(name: "DisableExtendedProductCarousel") {
          jsonValue
        }
    	ExtendedProductCarouselTitle: field(name: "ExtendedProductCarouselTitle") {
          jsonValue
        }
    	ExtendedProductCarouselButtonText: field(name: "ExtendedProductCarouselButtonText") {
          jsonValue
        }
    	ExtendedProductCarouselButtonFunctionality: field(name: "ExtendedProductCarouselButtonFunctionality") {
          jsonValue
        }
    	ExtendedProductCarouselDiscoverRfkId: field(name: "ExtendedProductCarouselDiscoverRfkId") {
          jsonValue
        }
    	ExtendedProductCarouselDiscoverPodID: field(name: "ExtendedProductCarouselDiscoverPodID") {
          jsonValue
        }
    	ExtendedProductCarouselDefaultItemsPerPageDesktop: field(name: "ExtendedProductCarouselDefaultItemsPerPageDesktop") {
          jsonValue
        }
    	ExtendedProductCarouselDefaultItemsPerPageMobile: field(name: "ExtendedProductCarouselDefaultItemsPerPageMobile") {
          jsonValue
        }
    	ExtendedProductCarouselAPIEndPoint: field(name: "ExtendedProductCarouselAPIEndPoint") {
          jsonValue
        }
      }
    }
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Feature/TTS/Components/Product Card Collection/Datasource Folder/Product Card Collection
- ID: "308e88f5-cd6e-4f8f-bafe-95a47dedefdc"
  Hint: Editable
  Value: 1
- ID: "34e81e40-1d4d-45b0-bcf1-a0ffe5521685"
  Hint: RenderingCssClass
  Value: "product-card-collection"
- ID: "7d8ae35f-9ed1-43b5-96a2-0a5f040d4e4e"
  Hint: Open Properties after Add
  Value: 0
- ID: "9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4"
  Hint: __Read Only
  Value: 
- ID: "a77e8568-1ab3-44f1-a664-b7c37ec7810d"
  Hint: Parameters Template
  Value: "{1224C08B-7CD8-4277-A953-8690AD778A6E}"
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "query:$site/*[@@name='Data']/*[@@templatename='Product Card Collection Folder']|query:$sharedSites/*[@@name='Data']/*[@@templatename='Product Card Collection Folder']"
- ID: "c39a90ce-0035-41bb-90f6-3c8a6ea87797"
  Hint: AddFieldEditorButton
  Value: 
- ID: "e829c217-5e94-4306-9c48-2634b094fdc2"
  Hint: OtherProperties
  Value: IsRenderingsWithDynamicPlaceholders=true
- ID: "f172b787-7b88-4bd5-ae4d-6308e102ef11"
  Hint: Enable Datasource Query
  Value: 
Languages:
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Promo
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250327T104822Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c5c10454-d41a-4427-a443-a329487c4bd5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250327T104822Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120931Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "88e466f3-a247-4623-b182-039201a56cf0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250407T110800Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: プロモ
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250327T104822Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c5c10454-d41a-4427-a443-a329487c4bd5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250327T104822Z
- Language: "zh-CN"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 促销
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250327T104822Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c5c10454-d41a-4427-a443-a329487c4bd5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250327T104822Z
