---
ID: "afdad0e1-5cb9-4009-bf72-0b17b4173709"
Parent: "f4fdc77c-6b9a-4b9f-9155-a9c21a858fd9"
Template: "f4fdc77c-6b9a-4b9f-9155-a9c21a858fd9"
Path: /sitecore/templates/Feature/TTS/Folders/Styles Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F9CECAC1-6B6E-4399-B7A7-78E9295CFCDF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180907T203519Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4417ede-060c-410b-9872-f6823cdac46c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180907T203545Z
