---
ID: "543621f0-eef2-43d1-aec5-fe0db0910e2c"
Parent: "2cf1a7a4-1a61-488c-9818-5cc128f0f567"
Template: "2cf1a7a4-1a61-488c-9818-5cc128f0f567"
Path: /sitecore/templates/Feature/TTS/Components/Forms/Sign Up Form/Folder Templates/Subscribe Mail Options Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{B3B0AF6B-D221-412D-B51C-385A1CCAFB7E}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181129T143624Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\markb
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\markb
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "62c8f73c-be5b-4c95-9204-c9f8bd602085"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240523T105559Z
