---
ID: "cedea892-429e-43fe-a0f0-4cc32209a11f"
Parent: "20b64303-212d-4fdc-b2f0-53c75186b60b"
Template: "20b64303-212d-4fdc-b2f0-53c75186b60b"
Path: /sitecore/templates/Feature/TTS/Components/ResetPassword/Rendering Parameters/ResetPassword/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c774e9ba-583b-43c4-853e-891c584c9a63"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240528T155857Z
