---
ID: "841f0738-296c-432c-9a46-1cab15a4b7e5"
Parent: "9fc65006-a293-4339-a252-9ed1ff854f14"
Template: "9fc65006-a293-4339-a252-9ed1ff854f14"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_HoverEffect/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "facb9ee6-ba13-4794-aa1f-25fe6a64bb73"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240423T091419Z
