---
ID: "ee7beb02-c6a4-4efd-b2ed-e97f158f63d3"
Parent: "8df2ec53-e547-43d6-b5dd-b5248ade4b62"
Template: "5fcbea3a-600f-4071-b694-b6b03f8f697a"
Path: /sitecore/content/TTS/TileShop/Home/My Account/Settings
SharedFields:
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 0
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "24b37ad6-7c2e-4f63-b438-a4c293f23e94"
      Hint: IsProtectedPage
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240625T052136Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "5884d6fa-a5d2-4dcd-843b-f0c98feea026"
      Hint: Title
      Value: SETTINGS
    - ID: "59cbee2d-30a2-4a03-9501-2e3e0d4e8ced"
      Hint: PageTitle
      Value: Settings
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "396ae4fb-d01c-4d50-be36-f9bb11b12096"
    - ID: "a85d2606-c144-4bba-9476-d31d5b8d2d55"
      Hint: NavigationTitle
      Value: SETTINGS
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tJcvpTqENg
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240814T193529Z
    - ID: "ef0df81f-e71f-4166-8770-67cf7c3a59ff"
      Hint: HideInNavigation
      Value: 1
