---
ID: "05b8b4e6-cb2d-4132-b3f8-62d0e13efc51"
Parent: "9cbb53e3-2646-4e38-805f-26aab3f07150"
Template: "9cbb53e3-2646-4e38-805f-26aab3f07150"
Path: /sitecore/templates/Feature/TTS/Components/Payment Credit History/Rendering Parameters/Payment Credit History/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3c78b4fa-ac23-4bb0-b2c7-a5ff70a70d77"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240707T070017Z
