---
ID: "0716aec0-c111-4fd0-a5d4-cca696aa3c43"
Parent: "ced9db70-c704-494e-9deb-5c49711e986c"
Template: "ced9db70-c704-494e-9deb-5c49711e986c"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_IsComponentClickable/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "188d6efb-691e-4624-a4cd-2f74f2ff3880"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240617T034304Z
