---
ID: "3236257c-44ca-4c82-9a57-12e2cf70a5b7"
Parent: "b333424f-c2c3-4cfd-b30a-7a351a5a0785"
Template: "b333424f-c2c3-4cfd-b30a-7a351a5a0785"
Path: /sitecore/templates/Feature/TTS/Components/Address Book/Rendering Parameters/AddressBook/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7710a879-6f8f-490e-8c41-280f6f14e903"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tanvi.vaid@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240607T150110Z
