---
ID: "735b973d-fb73-4cf1-b51e-a94c615bbc4f"
Parent: "ca64e231-3113-4f89-9bb5-268888cd0bac"
Template: "ca64e231-3113-4f89-9bb5-268888cd0bac"
Path: /sitecore/templates/Foundation/TTS/Navigation/_Navigation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240425T075258Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c4d8a097-60ff-4b71-9bde-1f27c294b003"
    - ID: "a85d2606-c144-4bba-9476-d31d5b8d2d55"
      Hint: NavigationTitle
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240425T075306Z
