---
ID: "1e37dd73-c0fa-4284-9222-0520ac955159"
Parent: "b673c640-4db2-4f4b-86dd-f489b22754f6"
Template: "b673c640-4db2-4f4b-86dd-f489b22754f6"
Path: /sitecore/templates/Feature/TTS/Components/Pay on Account/Rendering Parameters/Pay On Account/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "671723cc-3778-4402-bc74-ef4c5a1fec67"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240708T190424Z
