---
ID: "2ced3564-aa1c-4e04-a407-d3f88d16bf45"
Parent: "1538b8e6-9ce0-44ef-ba0a-3959d105fb2e"
Template: "1538b8e6-9ce0-44ef-ba0a-3959d105fb2e"
Path: /sitecore/templates/Feature/TTS/Components/PaymentWork Module/Rendering Parameters/PaymentWorks Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "81b77736-47c1-4a6d-9acf-c136174beedd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241224T073658Z
