---
ID: "85604fa8-32c2-4b78-8e71-31686c84640c"
Parent: "ef068365-88ef-494f-9fb0-d5a77e0c4f19"
Template: "ef068365-88ef-494f-9fb0-d5a77e0c4f19"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_AlignContentRight/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "775d4e03-f179-4e43-9cc2-b79871a3e26f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240531T043633Z
