---
ID: "e00fe889-25fd-4bfa-a83a-3ff8d6cd79b7"
Parent: "42791d7c-3d6f-4461-a9af-0e29ec446786"
Template: "42791d7c-3d6f-4461-a9af-0e29ec446786"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Media/_TabletImage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240414T081852Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2a646585-3e88-49a4-a60a-e7439c32fa59"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240723T053714Z
    - ID: "f8424eb8-e593-42c6-84cb-de891a9f8c0e"
      Hint: TabletImage
      Value: 
