---
ID: "48cb7291-592f-4677-95b4-5fffd04245a8"
Parent: "e42e3ed5-73c7-4784-ad73-24af00857731"
Template: "e42e3ed5-73c7-4784-ad73-24af00857731"
Path: /sitecore/templates/Feature/TTS/Components/Footer/Rendering Parameters/Footer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "523ccd8e-1abd-45c3-ab1d-6d52d20c5401"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rohit.gupta1@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240418T132003Z
