---
ID: "51bef3eb-2f65-453e-93eb-7606b03ea367"
Parent: "266c3935-6592-48df-b60b-2633ec394e0c"
Template: "266c3935-6592-48df-b60b-2633ec394e0c"
Path: /sitecore/templates/Feature/TTS/Components/Account Category Cards/Rendering Parameters/Account category Cards/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "774beee7-f682-4bcc-8369-e30fb751d590"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240609T081739Z
