---
ID: "5f631039-dd59-4b7e-a788-7b9bf3303b06"
Parent: "0dec2984-1119-411c-afe2-ce5811559892"
Template: "0dec2984-1119-411c-afe2-ce5811559892"
Path: /sitecore/templates/Feature/TTS/Components/Card/Rendering Parameters/Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6f5080fc-9ac8-4feb-88c9-3e50162a1b9c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240417T094429Z
