---
ID: "04193d42-abb5-48e4-af86-b0097fcebef9"
Parent: "0a9f769a-5443-4564-b7c5-cf1bad9ad240"
Template: "0a9f769a-5443-4564-b7c5-cf1bad9ad240"
Path: /sitecore/templates/Feature/TTS/Components/Products/Product Attributes/Rendering Parameters/Product Attributes/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0965707e-6fcf-4466-95b4-4864ffd08df1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sharma.varun@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240605T102122Z
