---
ID: "5fd737da-d0c5-4879-ab4b-eada4672d91d"
Parent: "cec82e8d-99f3-4fe1-ad05-a1e3870af510"
Template: "cec82e8d-99f3-4fe1-ad05-a1e3870af510"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_IsImageClickable/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53d3e550-7e72-4650-9669-7faa0bcbe3da"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rohit.gupta1@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240506T125413Z
