---
ID: "65d3a738-a003-4c39-a52b-d34f6f05d61d"
Parent: "b1084659-1b37-4e0a-a42d-501e117d6761"
Template: "b1084659-1b37-4e0a-a42d-501e117d6761"
Path: /sitecore/templates/Feature/TTS/Components/Create Or Change User/Rendering Parameters/CreateOrChangeUser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b504f0d2-00fd-442d-a713-53154f3eb0a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tanvi.vaid@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240704T114834Z
