---
ID: "9979295a-375d-405e-b9ca-112110002bbe"
Parent: "9776bf60-6531-464b-b67b-4da77789d7c9"
Template: "9776bf60-6531-464b-b67b-4da77789d7c9"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Links/_CTA/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240414T081852Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6393e9a2-a91d-4e27-8768-6d5f5bc9f795"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240414T082014Z
