---
ID: "7d733b8e-7a18-4648-8977-cd854f324991"
Parent: "14329a98-0ee0-4273-ba39-d1f6eea1a63b"
Template: "14329a98-0ee0-4273-ba39-d1f6eea1a63b"
Path: /sitecore/templates/Feature/TTS/Components/Header/Datasource Folder/SearchBar/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240421T144217Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "de6c8391-80a1-4e33-b1b6-5defe20a61da"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sharma.varun@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240421T144217Z
