---
ID: "91b48c29-e86d-4a59-aaec-d638286043f7"
Parent: "6b82daf3-ec25-4781-b588-17f46cf82e73"
Template: "6b82daf3-ec25-4781-b588-17f46cf82e73"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_IsIcon/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c7cf33f8-6db0-4faa-9b37-712df5123cf1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240514T110511Z
