---
ID: "47bea7a0-cbe4-4cfd-a2aa-2d47c9708f0c"
Parent: "04c4cfbc-cdfc-4b01-86b5-8f088425a043"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/TTS/TileShop/Presentation/Headless Variants/RegisterProUserWithCustomerID/Default
BranchID: "0fdac040-6cfb-4ae0-939e-2725bf202c31"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{AB87C9A2-3B46-4D1A-887D-5C48BBA0CC2B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240529T173202Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nndGgLsZ18
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nndGgLsZ18
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0daef839-c321-425e-ad70-b282731465e6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nndGgLsZ18
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240529T173202Z
