---
ID: "d535463f-3e36-48dd-b66b-11b9adb50aef"
Parent: "92337f5f-a1fb-417f-a0b1-ac95cf5ecdcf"
Template: "92337f5f-a1fb-417f-a0b1-ac95cf5ecdcf"
Path: /sitecore/templates/Feature/TTS/Components/My Projects/Rendering Parameters/My Projects/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63cdae13-7eec-430b-8509-d7d13e737aa3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240704T080535Z
