---
ID: "67205abb-49fe-4bbd-97c6-7d7f605ba31b"
Parent: "7c1b29b1-3be5-4c54-92dc-55b79e710926"
Template: "7c1b29b1-3be5-4c54-92dc-55b79e710926"
Path: /sitecore/templates/Feature/TTS/Components/Cards/Category Cards with Embed Links/Rendering Parameters/CategoryCardswithEmbedLinks/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6842bcab-bd63-41d3-b475-bdcd9428fdb1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240426T044558Z
