---
ID: "21fa2287-1620-43e1-b867-8d3d1c9c6afc"
Parent: "e9db4b6a-2bb0-4ca2-ae38-5a722a4bdb6d"
Template: "e9db4b6a-2bb0-4ca2-ae38-5a722a4bdb6d"
Path: /sitecore/templates/Feature/TTS/Components/Products/PDP Info/Rendering Parameters/PDP Info/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6ff445dd-72e7-441d-ab48-b03095982840"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sharma.varun@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240611T050712Z
