---
ID: "99ceebb7-4e5c-44a0-8941-63a91913b1ee"
Parent: "f3c97f22-0319-485a-aacc-beeee865d79c"
Template: "f3c97f22-0319-485a-aacc-beeee865d79c"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Tags/_SectionHeadingTag/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "866c90b2-5f63-4e93-b07a-e67dc545b2fa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240426T032820Z
