---
ID: "1443e00c-9c6d-4f96-a903-f6113ea292f8"
Parent: "29fbddec-c539-43e6-b670-2fdccf715a0a"
Template: "29fbddec-c539-43e6-b670-2fdccf715a0a"
Path: /sitecore/templates/Feature/TTS/Components/Cart/HeadingSectionCart/Rendering Parameters/HeadingSectionCart/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "07173952-0831-41db-9ee4-1c8f14886d33"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwani.kumar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240527T162616Z
