---
ID: "47d3e561-39f3-415f-b995-0e3738a23984"
Parent: "dfab94cf-a1da-4f32-b824-ea3035ed7da9"
Template: "dfab94cf-a1da-4f32-b824-ea3035ed7da9"
Path: /sitecore/templates/Feature/TTS/Components/Rewards Card/Rendering Parameters/Rewards Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "af8f1ce9-b197-48ff-99d9-a3a6185e9d7f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240701T100544Z
