---
ID: "f00bef0a-05d6-4e79-a71e-652fccdda301"
Parent: "8acab1b3-2f1f-4ec0-a65b-7aa86377b742"
Template: "8acab1b3-2f1f-4ec0-a65b-7aa86377b742"
Path: /sitecore/templates/Feature/TTS/Components/Cards/Category Cards with Embed Links/Folder Templates/CategoryCardswithEmbedLinks Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {1CC04AEB-0F43-4170-BD7D-B9CE8453F3CF}
    {8ACAB1B3-2F1F-4EC0-A65B-7AA86377B742}
    {A53B4353-B5E1-4B57-B4A1-7F2C8E518698}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8faf840f-fa58-4653-8991-8c5ce6bbf70e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240426T050649Z
