---
ID: "56d7695b-b69b-42be-9dea-3e8630ae666e"
Parent: "276529e2-d558-49f1-b2bd-8af6f0fb2e8d"
Template: "276529e2-d558-49f1-b2bd-8af6f0fb2e8d"
Path: /sitecore/templates/Feature/TTS/Components/Registration/RegisterProUserWithCustomerID/Rendering Parameters/RegisterProUserWithCustomerID/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "610f4c22-a4ce-4f5d-a75c-7e47462aa175"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aFU6oHBAEl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240521T101748Z
