---
ID: "f69495fe-e8ff-41ea-ae03-0be6df70fbb2"
Parent: "3dc3ab0a-dfcd-4f4c-a9d8-fee773e97c81"
Template: "3dc3ab0a-dfcd-4f4c-a9d8-fee773e97c81"
Path: /sitecore/templates/Feature/TTS/Common/Rendering Parameters/Toggle/_CTAHoverEffect/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1816ea73-f8d9-46b9-8e9b-294d1eeef00a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240904T074831Z
