---
ID: "56c617a5-e669-4386-aa39-a59fb2264e35"
Parent: "5f06f3bd-6bf1-4f5d-9aaa-efd8ca191968"
Template: "9fba7db0-0937-453e-8801-2684a4239b3e"
Path: /sitecore/content/TTS/TileShop/Home/application
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{7C62719A-826E-4A7E-889D-375EAC8C09FF}"
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 0
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1100
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{2A7432E9-1906-4EAE-8579-788B225EBA0D}"
          p:before="*"
          s:ds="local:/Data/Floor Tile"
          s:id="{D4812085-143E-4281-9719-EBD203E5DEDD}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;HeadingSize=h2&amp;HeadingTag=h2&amp;IsPinterestEnable=1&amp;Opacity&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
          s:ph="/headless-main/column-1-2" />
        <r
          uid="{BDEEF258-ACD3-4D0C-9735-EA4C1DBA1F91}"
          p:after="r[@uid='{2A7432E9-1906-4EAE-8579-788B225EBA0D}']"
          s:ds="local:/Data/Wall Tile"
          s:id="{D4812085-143E-4281-9719-EBD203E5DEDD}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;HeadingSize=h2&amp;HeadingTag=h2&amp;IsPinterestEnable=1&amp;Opacity&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
          s:ph="/headless-main/column-2-2" />
        <r
          uid="{E13D7A04-2E5D-4393-B9AD-F31292B4CA52}"
          p:after="r[@uid='{BDEEF258-ACD3-4D0C-9735-EA4C1DBA1F91}']"
          s:ds="local:/Data/Accent Tile"
          s:id="{D4812085-143E-4281-9719-EBD203E5DEDD}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;HeadingSize=h2&amp;HeadingTag=h2&amp;IsPinterestEnable=1&amp;Opacity&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=5"
          s:ph="/headless-main/column-3-2" />
        <r
          uid="{EBF2B0D3-2FD2-4055-8B8A-3CFC9C539306}"
          p:after="r[@uid='{E13D7A04-2E5D-4393-B9AD-F31292B4CA52}']"
          s:ds="local:/Data/Backsplash Tile"
          s:id="{D4812085-143E-4281-9719-EBD203E5DEDD}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;HeadingSize=h2&amp;HeadingTag=h2&amp;IsPinterestEnable=1&amp;Opacity&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=6"
          s:ph="/headless-main/column-4-2" />
        <r
          uid="{633BAE49-9C64-4B7C-B9E0-B9814066396D}"
          p:after="r[@uid='{EBF2B0D3-2FD2-4055-8B8A-3CFC9C539306}']"
          s:ds="local:/Data/Pool Tile"
          s:id="{D4812085-143E-4281-9719-EBD203E5DEDD}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;HeadingSize=h2&amp;HeadingTag=h2&amp;IsPinterestEnable=1&amp;Opacity&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=7"
          s:ph="/headless-main/column-5-2" />
        <r
          uid="{7D0EEE6A-A130-4F98-93C3-FEECF3BF5884}"
          p:after="r[@uid='{633BAE49-9C64-4B7C-B9E0-B9814066396D}']"
          s:ds=""
          s:id="{5283878D-861F-4748-8A17-B417BAA1A017}"
          s:par="CSSStyles"
          s:ph="headless-main" />
        <r
          uid="{48BCF29B-A982-4868-A0D8-8D978278A7AD}"
          p:after="r[@uid='{7D0EEE6A-A130-4F98-93C3-FEECF3BF5884}']"
          s:ds="local:/Data/Title"
          s:id="{83969962-2802-423F-B7D8-8406B9243F02}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7B516A674E-D77C-49FB-BB53-48BD6CD32F58%7D&amp;Styles=%7B97ECAA03-83DD-425D-9F0E-E9DE6AB88294%7D%7C%7B9B3796C3-A793-4C3E-8F64-AD7203028B3E%7D&amp;HeadingSize=h5&amp;HeadingTag=h5&amp;CTAColor=Black&amp;CTASize=Small&amp;IsCTATextInCaps=1&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=8"
          s:ph="headless-main" />
        <r
          uid="{9C01CCEF-738F-4F10-986E-BEBA4E4858FC}"
          p:after="*[1=2]"
          s:ds=""
          s:id="{15CABDFF-FFD9-48F4-826D-A4C3D7868D3A}"
          s:par="ColumnWidth1=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D%7C%7B37B8F625-37B3-41B9-BA85-D31AA5A44463%7D&amp;ColumnWidth2=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D%7C%7B37B8F625-37B3-41B9-BA85-D31AA5A44463%7D&amp;ColumnWidth3=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D%7C%7B37B8F625-37B3-41B9-BA85-D31AA5A44463%7D&amp;ColumnWidth4=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D%7C%7B37B8F625-37B3-41B9-BA85-D31AA5A44463%7D&amp;ColumnWidth5=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D%7C%7B37B8F625-37B3-41B9-BA85-D31AA5A44463%7D&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;SplitterSize=2&amp;EnabledPlaceholders=1%2C2%2C3%2C4%2C5&amp;FieldNames&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles&amp;Styles8&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
          s:ph="headless-main" />
      </d>
    </r>
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181008T180942Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jimg
    - ID: "5884d6fa-a5d2-4dcd-843b-f0c98feea026"
      Hint: Title
      Value: Application
    - ID: "59cbee2d-30a2-4a03-9501-2e3e0d4e8ced"
      Hint: PageTitle
      Value: "Tile by Application - The Tile Shop"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\smallaya
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b662ee92-c77d-47c7-93c9-74cd39d8de6f"
    - ID: "a85d2606-c144-4bba-9476-d31d5b8d2d55"
      Hint: NavigationTitle
      Value: Application
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tJcvpTqENg
    - ID: "c062edba-a9e6-405c-a204-82db37a4c2d5"
      Hint: MetaDescription
      Value: "Shop our huge selection of tile by application and get expert advice and assistance from The Tile Shop. Visit us today for your free design consultation!"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240814T193436Z
