---
ID: "b6558662-6df8-4252-b9bd-202d0653431b"
Parent: "461f7ada-aedf-4d81-98bf-b43339205691"
Template: "461f7ada-aedf-4d81-98bf-b43339205691"
Path: /sitecore/templates/Feature/TTS/Components/Multi Asset Banner/Rendering Parameters/Multi Asset Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7bfcd34c-c603-4000-b8f5-82790ede9401"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sharma.varun@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240507T105018Z
