---
ID: "10670fe0-78fa-444f-a39f-e2eeecac02a9"
Parent: "2abd5a10-f88a-4952-88c6-7cc88ad499a2"
Template: "2abd5a10-f88a-4952-88c6-7cc88ad499a2"
Path: /sitecore/templates/Feature/TTS/Common/Interface Templates/Media/_CssClass/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240414T081852Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jaydip.amrutlal@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c1954860-0eb7-4695-91e4-b9dc8de5f62c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rohit.gupta1@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240418T132048Z
    - ID: "ffd1abac-16c2-42ed-ab0d-7aa8a7159494"
      Hint: CssClass
      Value: KFhero2
