---
ID: "dafb85d7-a38e-4287-a533-97c6d6de6277"
Parent: "1a8e56d5-0209-4ea1-a8a0-e4b77cb54c26"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: /sitecore/content/TTS/TileShop/Dictionary/PDP Info/Application Callout
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: PDPInfo_application_callout
Languages:
- Language: en
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: *Please note that these are only recommendations and in some cases the products may be suitable for installation in additional spaces.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240705T065531Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7f692389-74e9-4006-97bb-093db42d6cba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kWcqIa9tCD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240705T065601Z
