---
ID: "a8abe114-e571-41de-bd87-53b34b4024bf"
Parent: "fccc734c-9066-4d5a-b74f-305f42477b03"
Template: "fccc734c-9066-4d5a-b74f-305f42477b03"
Path: /sitecore/templates/Feature/TTS/Components/Registration/RegisterPersonalUser/Rendering Parameters/RegisterPersonalUser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9997ecf7-d0ac-4fdf-84df-64fc2773265b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rohit.gupta1@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240429T081619Z
