---
ID: "0f547a3f-309e-43b4-bc5d-fdde0cdd086a"
Parent: "88a0e54b-f65e-4937-b34b-4f72d072a611"
Template: "88a0e54b-f65e-4937-b34b-4f72d072a611"
Path: /sitecore/templates/Feature/TTS/Components/Image Gallery/Folder Templates/ImageGallery Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C67C05E7-A47D-4A7C-B52B-C66B5944E4D7}
    {88A0E54B-F65E-4937-B34B-4F72D072A611}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2f0be7f8-335a-4b5d-841b-f577d18b0b9f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sailaab.tirkey@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240426T121700Z
