---
ID: "e519e8fd-400b-4ef0-8651-5bf089a76e2b"
Parent: "c99e218e-0c3d-4a7f-b367-d073decf04e8"
Template: "c99e218e-0c3d-4a7f-b367-d073decf04e8"
Path: /sitecore/templates/Feature/TTS/Components/Registration Confirmation/Rendering Parameters/Registration Confirmation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5ba3e6f0-e879-4abf-be49-9b3259dceb09"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srinivasan.krishnamurthy@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240521T040802Z
